# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.6.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.6.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Sheng/WorkSpace/transition-notes

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Sheng/WorkSpace/transition-notes

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.6.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.6.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Sheng/WorkSpace/transition-notes/CMakeFiles /Users/Sheng/WorkSpace/transition-notes/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Sheng/WorkSpace/transition-notes/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SyntaxNet

# Build rule for target.
SyntaxNet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SyntaxNet
.PHONY : SyntaxNet

# fast build rule for target.
SyntaxNet/fast:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/build
.PHONY : SyntaxNet/fast

src/cli_main.o: src/cli_main.cc.o

.PHONY : src/cli_main.o

# target to build an object file
src/cli_main.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/cli_main.cc.o
.PHONY : src/cli_main.cc.o

src/cli_main.i: src/cli_main.cc.i

.PHONY : src/cli_main.i

# target to preprocess a source file
src/cli_main.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/cli_main.cc.i
.PHONY : src/cli_main.cc.i

src/cli_main.s: src/cli_main.cc.s

.PHONY : src/cli_main.s

# target to generate assembly for a file
src/cli_main.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/cli_main.cc.s
.PHONY : src/cli_main.cc.s

src/feature/embedding_feature_extractor.o: src/feature/embedding_feature_extractor.cc.o

.PHONY : src/feature/embedding_feature_extractor.o

# target to build an object file
src/feature/embedding_feature_extractor.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/feature/embedding_feature_extractor.cc.o
.PHONY : src/feature/embedding_feature_extractor.cc.o

src/feature/embedding_feature_extractor.i: src/feature/embedding_feature_extractor.cc.i

.PHONY : src/feature/embedding_feature_extractor.i

# target to preprocess a source file
src/feature/embedding_feature_extractor.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/feature/embedding_feature_extractor.cc.i
.PHONY : src/feature/embedding_feature_extractor.cc.i

src/feature/embedding_feature_extractor.s: src/feature/embedding_feature_extractor.cc.s

.PHONY : src/feature/embedding_feature_extractor.s

# target to generate assembly for a file
src/feature/embedding_feature_extractor.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/feature/embedding_feature_extractor.cc.s
.PHONY : src/feature/embedding_feature_extractor.cc.s

src/feature/feature.o: src/feature/feature.cc.o

.PHONY : src/feature/feature.o

# target to build an object file
src/feature/feature.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/feature/feature.cc.o
.PHONY : src/feature/feature.cc.o

src/feature/feature.i: src/feature/feature.cc.i

.PHONY : src/feature/feature.i

# target to preprocess a source file
src/feature/feature.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/feature/feature.cc.i
.PHONY : src/feature/feature.cc.i

src/feature/feature.s: src/feature/feature.cc.s

.PHONY : src/feature/feature.s

# target to generate assembly for a file
src/feature/feature.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/feature/feature.cc.s
.PHONY : src/feature/feature.cc.s

src/feature/feature_extractor.o: src/feature/feature_extractor.cc.o

.PHONY : src/feature/feature_extractor.o

# target to build an object file
src/feature/feature_extractor.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/feature/feature_extractor.cc.o
.PHONY : src/feature/feature_extractor.cc.o

src/feature/feature_extractor.i: src/feature/feature_extractor.cc.i

.PHONY : src/feature/feature_extractor.i

# target to preprocess a source file
src/feature/feature_extractor.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/feature/feature_extractor.cc.i
.PHONY : src/feature/feature_extractor.cc.i

src/feature/feature_extractor.s: src/feature/feature_extractor.cc.s

.PHONY : src/feature/feature_extractor.s

# target to generate assembly for a file
src/feature/feature_extractor.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/feature/feature_extractor.cc.s
.PHONY : src/feature/feature_extractor.cc.s

src/feature/parser_features.o: src/feature/parser_features.cc.o

.PHONY : src/feature/parser_features.o

# target to build an object file
src/feature/parser_features.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/feature/parser_features.cc.o
.PHONY : src/feature/parser_features.cc.o

src/feature/parser_features.i: src/feature/parser_features.cc.i

.PHONY : src/feature/parser_features.i

# target to preprocess a source file
src/feature/parser_features.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/feature/parser_features.cc.i
.PHONY : src/feature/parser_features.cc.i

src/feature/parser_features.s: src/feature/parser_features.cc.s

.PHONY : src/feature/parser_features.s

# target to generate assembly for a file
src/feature/parser_features.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/feature/parser_features.cc.s
.PHONY : src/feature/parser_features.cc.s

src/feature/sentence_features.o: src/feature/sentence_features.cc.o

.PHONY : src/feature/sentence_features.o

# target to build an object file
src/feature/sentence_features.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/feature/sentence_features.cc.o
.PHONY : src/feature/sentence_features.cc.o

src/feature/sentence_features.i: src/feature/sentence_features.cc.i

.PHONY : src/feature/sentence_features.i

# target to preprocess a source file
src/feature/sentence_features.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/feature/sentence_features.cc.i
.PHONY : src/feature/sentence_features.cc.i

src/feature/sentence_features.s: src/feature/sentence_features.cc.s

.PHONY : src/feature/sentence_features.s

# target to generate assembly for a file
src/feature/sentence_features.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/feature/sentence_features.cc.s
.PHONY : src/feature/sentence_features.cc.s

src/fml/fml_parser.o: src/fml/fml_parser.cc.o

.PHONY : src/fml/fml_parser.o

# target to build an object file
src/fml/fml_parser.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/fml/fml_parser.cc.o
.PHONY : src/fml/fml_parser.cc.o

src/fml/fml_parser.i: src/fml/fml_parser.cc.i

.PHONY : src/fml/fml_parser.i

# target to preprocess a source file
src/fml/fml_parser.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/fml/fml_parser.cc.i
.PHONY : src/fml/fml_parser.cc.i

src/fml/fml_parser.s: src/fml/fml_parser.cc.s

.PHONY : src/fml/fml_parser.s

# target to generate assembly for a file
src/fml/fml_parser.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/fml/fml_parser.cc.s
.PHONY : src/fml/fml_parser.cc.s

src/io/document_format.o: src/io/document_format.cc.o

.PHONY : src/io/document_format.o

# target to build an object file
src/io/document_format.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/io/document_format.cc.o
.PHONY : src/io/document_format.cc.o

src/io/document_format.i: src/io/document_format.cc.i

.PHONY : src/io/document_format.i

# target to preprocess a source file
src/io/document_format.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/io/document_format.cc.i
.PHONY : src/io/document_format.cc.i

src/io/document_format.s: src/io/document_format.cc.s

.PHONY : src/io/document_format.s

# target to generate assembly for a file
src/io/document_format.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/io/document_format.cc.s
.PHONY : src/io/document_format.cc.s

src/io/text_reader.o: src/io/text_reader.cc.o

.PHONY : src/io/text_reader.o

# target to build an object file
src/io/text_reader.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/io/text_reader.cc.o
.PHONY : src/io/text_reader.cc.o

src/io/text_reader.i: src/io/text_reader.cc.i

.PHONY : src/io/text_reader.i

# target to preprocess a source file
src/io/text_reader.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/io/text_reader.cc.i
.PHONY : src/io/text_reader.cc.i

src/io/text_reader.s: src/io/text_reader.cc.s

.PHONY : src/io/text_reader.s

# target to generate assembly for a file
src/io/text_reader.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/io/text_reader.cc.s
.PHONY : src/io/text_reader.cc.s

src/lexicon/lexicon_builder.o: src/lexicon/lexicon_builder.cc.o

.PHONY : src/lexicon/lexicon_builder.o

# target to build an object file
src/lexicon/lexicon_builder.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/lexicon/lexicon_builder.cc.o
.PHONY : src/lexicon/lexicon_builder.cc.o

src/lexicon/lexicon_builder.i: src/lexicon/lexicon_builder.cc.i

.PHONY : src/lexicon/lexicon_builder.i

# target to preprocess a source file
src/lexicon/lexicon_builder.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/lexicon/lexicon_builder.cc.i
.PHONY : src/lexicon/lexicon_builder.cc.i

src/lexicon/lexicon_builder.s: src/lexicon/lexicon_builder.cc.s

.PHONY : src/lexicon/lexicon_builder.s

# target to generate assembly for a file
src/lexicon/lexicon_builder.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/lexicon/lexicon_builder.cc.s
.PHONY : src/lexicon/lexicon_builder.cc.s

src/lexicon/term_frequency_map.o: src/lexicon/term_frequency_map.cc.o

.PHONY : src/lexicon/term_frequency_map.o

# target to build an object file
src/lexicon/term_frequency_map.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/lexicon/term_frequency_map.cc.o
.PHONY : src/lexicon/term_frequency_map.cc.o

src/lexicon/term_frequency_map.i: src/lexicon/term_frequency_map.cc.i

.PHONY : src/lexicon/term_frequency_map.i

# target to preprocess a source file
src/lexicon/term_frequency_map.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/lexicon/term_frequency_map.cc.i
.PHONY : src/lexicon/term_frequency_map.cc.i

src/lexicon/term_frequency_map.s: src/lexicon/term_frequency_map.cc.s

.PHONY : src/lexicon/term_frequency_map.s

# target to generate assembly for a file
src/lexicon/term_frequency_map.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/lexicon/term_frequency_map.cc.s
.PHONY : src/lexicon/term_frequency_map.cc.s

src/model/greedy_parser.o: src/model/greedy_parser.cc.o

.PHONY : src/model/greedy_parser.o

# target to build an object file
src/model/greedy_parser.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/model/greedy_parser.cc.o
.PHONY : src/model/greedy_parser.cc.o

src/model/greedy_parser.i: src/model/greedy_parser.cc.i

.PHONY : src/model/greedy_parser.i

# target to preprocess a source file
src/model/greedy_parser.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/model/greedy_parser.cc.i
.PHONY : src/model/greedy_parser.cc.i

src/model/greedy_parser.s: src/model/greedy_parser.cc.s

.PHONY : src/model/greedy_parser.s

# target to generate assembly for a file
src/model/greedy_parser.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/model/greedy_parser.cc.s
.PHONY : src/model/greedy_parser.cc.s

src/mxnet-cpp/executor.o: src/mxnet-cpp/executor.cc.o

.PHONY : src/mxnet-cpp/executor.o

# target to build an object file
src/mxnet-cpp/executor.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/mxnet-cpp/executor.cc.o
.PHONY : src/mxnet-cpp/executor.cc.o

src/mxnet-cpp/executor.i: src/mxnet-cpp/executor.cc.i

.PHONY : src/mxnet-cpp/executor.i

# target to preprocess a source file
src/mxnet-cpp/executor.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/mxnet-cpp/executor.cc.i
.PHONY : src/mxnet-cpp/executor.cc.i

src/mxnet-cpp/executor.s: src/mxnet-cpp/executor.cc.s

.PHONY : src/mxnet-cpp/executor.s

# target to generate assembly for a file
src/mxnet-cpp/executor.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/mxnet-cpp/executor.cc.s
.PHONY : src/mxnet-cpp/executor.cc.s

src/mxnet-cpp/io.o: src/mxnet-cpp/io.cc.o

.PHONY : src/mxnet-cpp/io.o

# target to build an object file
src/mxnet-cpp/io.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/mxnet-cpp/io.cc.o
.PHONY : src/mxnet-cpp/io.cc.o

src/mxnet-cpp/io.i: src/mxnet-cpp/io.cc.i

.PHONY : src/mxnet-cpp/io.i

# target to preprocess a source file
src/mxnet-cpp/io.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/mxnet-cpp/io.cc.i
.PHONY : src/mxnet-cpp/io.cc.i

src/mxnet-cpp/io.s: src/mxnet-cpp/io.cc.s

.PHONY : src/mxnet-cpp/io.s

# target to generate assembly for a file
src/mxnet-cpp/io.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/mxnet-cpp/io.cc.s
.PHONY : src/mxnet-cpp/io.cc.s

src/mxnet-cpp/kvstore.o: src/mxnet-cpp/kvstore.cc.o

.PHONY : src/mxnet-cpp/kvstore.o

# target to build an object file
src/mxnet-cpp/kvstore.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/mxnet-cpp/kvstore.cc.o
.PHONY : src/mxnet-cpp/kvstore.cc.o

src/mxnet-cpp/kvstore.i: src/mxnet-cpp/kvstore.cc.i

.PHONY : src/mxnet-cpp/kvstore.i

# target to preprocess a source file
src/mxnet-cpp/kvstore.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/mxnet-cpp/kvstore.cc.i
.PHONY : src/mxnet-cpp/kvstore.cc.i

src/mxnet-cpp/kvstore.s: src/mxnet-cpp/kvstore.cc.s

.PHONY : src/mxnet-cpp/kvstore.s

# target to generate assembly for a file
src/mxnet-cpp/kvstore.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/mxnet-cpp/kvstore.cc.s
.PHONY : src/mxnet-cpp/kvstore.cc.s

src/mxnet-cpp/ndarray.o: src/mxnet-cpp/ndarray.cc.o

.PHONY : src/mxnet-cpp/ndarray.o

# target to build an object file
src/mxnet-cpp/ndarray.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/mxnet-cpp/ndarray.cc.o
.PHONY : src/mxnet-cpp/ndarray.cc.o

src/mxnet-cpp/ndarray.i: src/mxnet-cpp/ndarray.cc.i

.PHONY : src/mxnet-cpp/ndarray.i

# target to preprocess a source file
src/mxnet-cpp/ndarray.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/mxnet-cpp/ndarray.cc.i
.PHONY : src/mxnet-cpp/ndarray.cc.i

src/mxnet-cpp/ndarray.s: src/mxnet-cpp/ndarray.cc.s

.PHONY : src/mxnet-cpp/ndarray.s

# target to generate assembly for a file
src/mxnet-cpp/ndarray.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/mxnet-cpp/ndarray.cc.s
.PHONY : src/mxnet-cpp/ndarray.cc.s

src/mxnet-cpp/operator.o: src/mxnet-cpp/operator.cc.o

.PHONY : src/mxnet-cpp/operator.o

# target to build an object file
src/mxnet-cpp/operator.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/mxnet-cpp/operator.cc.o
.PHONY : src/mxnet-cpp/operator.cc.o

src/mxnet-cpp/operator.i: src/mxnet-cpp/operator.cc.i

.PHONY : src/mxnet-cpp/operator.i

# target to preprocess a source file
src/mxnet-cpp/operator.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/mxnet-cpp/operator.cc.i
.PHONY : src/mxnet-cpp/operator.cc.i

src/mxnet-cpp/operator.s: src/mxnet-cpp/operator.cc.s

.PHONY : src/mxnet-cpp/operator.s

# target to generate assembly for a file
src/mxnet-cpp/operator.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/mxnet-cpp/operator.cc.s
.PHONY : src/mxnet-cpp/operator.cc.s

src/mxnet-cpp/optimizer.o: src/mxnet-cpp/optimizer.cc.o

.PHONY : src/mxnet-cpp/optimizer.o

# target to build an object file
src/mxnet-cpp/optimizer.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/mxnet-cpp/optimizer.cc.o
.PHONY : src/mxnet-cpp/optimizer.cc.o

src/mxnet-cpp/optimizer.i: src/mxnet-cpp/optimizer.cc.i

.PHONY : src/mxnet-cpp/optimizer.i

# target to preprocess a source file
src/mxnet-cpp/optimizer.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/mxnet-cpp/optimizer.cc.i
.PHONY : src/mxnet-cpp/optimizer.cc.i

src/mxnet-cpp/optimizer.s: src/mxnet-cpp/optimizer.cc.s

.PHONY : src/mxnet-cpp/optimizer.s

# target to generate assembly for a file
src/mxnet-cpp/optimizer.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/mxnet-cpp/optimizer.cc.s
.PHONY : src/mxnet-cpp/optimizer.cc.s

src/mxnet-cpp/symbol.o: src/mxnet-cpp/symbol.cc.o

.PHONY : src/mxnet-cpp/symbol.o

# target to build an object file
src/mxnet-cpp/symbol.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/mxnet-cpp/symbol.cc.o
.PHONY : src/mxnet-cpp/symbol.cc.o

src/mxnet-cpp/symbol.i: src/mxnet-cpp/symbol.cc.i

.PHONY : src/mxnet-cpp/symbol.i

# target to preprocess a source file
src/mxnet-cpp/symbol.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/mxnet-cpp/symbol.cc.i
.PHONY : src/mxnet-cpp/symbol.cc.i

src/mxnet-cpp/symbol.s: src/mxnet-cpp/symbol.cc.s

.PHONY : src/mxnet-cpp/symbol.s

# target to generate assembly for a file
src/mxnet-cpp/symbol.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/mxnet-cpp/symbol.cc.s
.PHONY : src/mxnet-cpp/symbol.cc.s

src/parser/arc_standard_transitions.o: src/parser/arc_standard_transitions.cc.o

.PHONY : src/parser/arc_standard_transitions.o

# target to build an object file
src/parser/arc_standard_transitions.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/parser/arc_standard_transitions.cc.o
.PHONY : src/parser/arc_standard_transitions.cc.o

src/parser/arc_standard_transitions.i: src/parser/arc_standard_transitions.cc.i

.PHONY : src/parser/arc_standard_transitions.i

# target to preprocess a source file
src/parser/arc_standard_transitions.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/parser/arc_standard_transitions.cc.i
.PHONY : src/parser/arc_standard_transitions.cc.i

src/parser/arc_standard_transitions.s: src/parser/arc_standard_transitions.cc.s

.PHONY : src/parser/arc_standard_transitions.s

# target to generate assembly for a file
src/parser/arc_standard_transitions.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/parser/arc_standard_transitions.cc.s
.PHONY : src/parser/arc_standard_transitions.cc.s

src/parser/parser_state.o: src/parser/parser_state.cc.o

.PHONY : src/parser/parser_state.o

# target to build an object file
src/parser/parser_state.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/parser/parser_state.cc.o
.PHONY : src/parser/parser_state.cc.o

src/parser/parser_state.i: src/parser/parser_state.cc.i

.PHONY : src/parser/parser_state.i

# target to preprocess a source file
src/parser/parser_state.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/parser/parser_state.cc.i
.PHONY : src/parser/parser_state.cc.i

src/parser/parser_state.s: src/parser/parser_state.cc.s

.PHONY : src/parser/parser_state.s

# target to generate assembly for a file
src/parser/parser_state.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/parser/parser_state.cc.s
.PHONY : src/parser/parser_state.cc.s

src/parser/parser_transitions.o: src/parser/parser_transitions.cc.o

.PHONY : src/parser/parser_transitions.o

# target to build an object file
src/parser/parser_transitions.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/parser/parser_transitions.cc.o
.PHONY : src/parser/parser_transitions.cc.o

src/parser/parser_transitions.i: src/parser/parser_transitions.cc.i

.PHONY : src/parser/parser_transitions.i

# target to preprocess a source file
src/parser/parser_transitions.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/parser/parser_transitions.cc.i
.PHONY : src/parser/parser_transitions.cc.i

src/parser/parser_transitions.s: src/parser/parser_transitions.cc.s

.PHONY : src/parser/parser_transitions.s

# target to generate assembly for a file
src/parser/parser_transitions.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/parser/parser_transitions.cc.s
.PHONY : src/parser/parser_transitions.cc.s

src/parser/tagger_transitions.o: src/parser/tagger_transitions.cc.o

.PHONY : src/parser/tagger_transitions.o

# target to build an object file
src/parser/tagger_transitions.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/parser/tagger_transitions.cc.o
.PHONY : src/parser/tagger_transitions.cc.o

src/parser/tagger_transitions.i: src/parser/tagger_transitions.cc.i

.PHONY : src/parser/tagger_transitions.i

# target to preprocess a source file
src/parser/tagger_transitions.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/parser/tagger_transitions.cc.i
.PHONY : src/parser/tagger_transitions.cc.i

src/parser/tagger_transitions.s: src/parser/tagger_transitions.cc.s

.PHONY : src/parser/tagger_transitions.s

# target to generate assembly for a file
src/parser/tagger_transitions.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/parser/tagger_transitions.cc.s
.PHONY : src/parser/tagger_transitions.cc.s

src/sentence_batch.o: src/sentence_batch.cc.o

.PHONY : src/sentence_batch.o

# target to build an object file
src/sentence_batch.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/sentence_batch.cc.o
.PHONY : src/sentence_batch.cc.o

src/sentence_batch.i: src/sentence_batch.cc.i

.PHONY : src/sentence_batch.i

# target to preprocess a source file
src/sentence_batch.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/sentence_batch.cc.i
.PHONY : src/sentence_batch.cc.i

src/sentence_batch.s: src/sentence_batch.cc.s

.PHONY : src/sentence_batch.s

# target to generate assembly for a file
src/sentence_batch.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/sentence_batch.cc.s
.PHONY : src/sentence_batch.cc.s

src/utils/registry.o: src/utils/registry.cc.o

.PHONY : src/utils/registry.o

# target to build an object file
src/utils/registry.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/utils/registry.cc.o
.PHONY : src/utils/registry.cc.o

src/utils/registry.i: src/utils/registry.cc.i

.PHONY : src/utils/registry.i

# target to preprocess a source file
src/utils/registry.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/utils/registry.cc.i
.PHONY : src/utils/registry.cc.i

src/utils/registry.s: src/utils/registry.cc.s

.PHONY : src/utils/registry.s

# target to generate assembly for a file
src/utils/registry.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/utils/registry.cc.s
.PHONY : src/utils/registry.cc.s

src/utils/shared_store.o: src/utils/shared_store.cc.o

.PHONY : src/utils/shared_store.o

# target to build an object file
src/utils/shared_store.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/utils/shared_store.cc.o
.PHONY : src/utils/shared_store.cc.o

src/utils/shared_store.i: src/utils/shared_store.cc.i

.PHONY : src/utils/shared_store.i

# target to preprocess a source file
src/utils/shared_store.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/utils/shared_store.cc.i
.PHONY : src/utils/shared_store.cc.i

src/utils/shared_store.s: src/utils/shared_store.cc.s

.PHONY : src/utils/shared_store.s

# target to generate assembly for a file
src/utils/shared_store.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/utils/shared_store.cc.s
.PHONY : src/utils/shared_store.cc.s

src/utils/task_context.o: src/utils/task_context.cc.o

.PHONY : src/utils/task_context.o

# target to build an object file
src/utils/task_context.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/utils/task_context.cc.o
.PHONY : src/utils/task_context.cc.o

src/utils/task_context.i: src/utils/task_context.cc.i

.PHONY : src/utils/task_context.i

# target to preprocess a source file
src/utils/task_context.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/utils/task_context.cc.i
.PHONY : src/utils/task_context.cc.i

src/utils/task_context.s: src/utils/task_context.cc.s

.PHONY : src/utils/task_context.s

# target to generate assembly for a file
src/utils/task_context.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/utils/task_context.cc.s
.PHONY : src/utils/task_context.cc.s

src/utils/task_spec.o: src/utils/task_spec.cc.o

.PHONY : src/utils/task_spec.o

# target to build an object file
src/utils/task_spec.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/utils/task_spec.cc.o
.PHONY : src/utils/task_spec.cc.o

src/utils/task_spec.i: src/utils/task_spec.cc.i

.PHONY : src/utils/task_spec.i

# target to preprocess a source file
src/utils/task_spec.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/utils/task_spec.cc.i
.PHONY : src/utils/task_spec.cc.i

src/utils/task_spec.s: src/utils/task_spec.cc.s

.PHONY : src/utils/task_spec.s

# target to generate assembly for a file
src/utils/task_spec.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/utils/task_spec.cc.s
.PHONY : src/utils/task_spec.cc.s

src/utils/utils.o: src/utils/utils.cc.o

.PHONY : src/utils/utils.o

# target to build an object file
src/utils/utils.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/utils/utils.cc.o
.PHONY : src/utils/utils.cc.o

src/utils/utils.i: src/utils/utils.cc.i

.PHONY : src/utils/utils.i

# target to preprocess a source file
src/utils/utils.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/utils/utils.cc.i
.PHONY : src/utils/utils.cc.i

src/utils/utils.s: src/utils/utils.cc.s

.PHONY : src/utils/utils.s

# target to generate assembly for a file
src/utils/utils.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/utils/utils.cc.s
.PHONY : src/utils/utils.cc.s

src/utils/work_space.o: src/utils/work_space.cc.o

.PHONY : src/utils/work_space.o

# target to build an object file
src/utils/work_space.cc.o:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/utils/work_space.cc.o
.PHONY : src/utils/work_space.cc.o

src/utils/work_space.i: src/utils/work_space.cc.i

.PHONY : src/utils/work_space.i

# target to preprocess a source file
src/utils/work_space.cc.i:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/utils/work_space.cc.i
.PHONY : src/utils/work_space.cc.i

src/utils/work_space.s: src/utils/work_space.cc.s

.PHONY : src/utils/work_space.s

# target to generate assembly for a file
src/utils/work_space.cc.s:
	$(MAKE) -f CMakeFiles/SyntaxNet.dir/build.make CMakeFiles/SyntaxNet.dir/src/utils/work_space.cc.s
.PHONY : src/utils/work_space.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SyntaxNet"
	@echo "... src/cli_main.o"
	@echo "... src/cli_main.i"
	@echo "... src/cli_main.s"
	@echo "... src/feature/embedding_feature_extractor.o"
	@echo "... src/feature/embedding_feature_extractor.i"
	@echo "... src/feature/embedding_feature_extractor.s"
	@echo "... src/feature/feature.o"
	@echo "... src/feature/feature.i"
	@echo "... src/feature/feature.s"
	@echo "... src/feature/feature_extractor.o"
	@echo "... src/feature/feature_extractor.i"
	@echo "... src/feature/feature_extractor.s"
	@echo "... src/feature/parser_features.o"
	@echo "... src/feature/parser_features.i"
	@echo "... src/feature/parser_features.s"
	@echo "... src/feature/sentence_features.o"
	@echo "... src/feature/sentence_features.i"
	@echo "... src/feature/sentence_features.s"
	@echo "... src/fml/fml_parser.o"
	@echo "... src/fml/fml_parser.i"
	@echo "... src/fml/fml_parser.s"
	@echo "... src/io/document_format.o"
	@echo "... src/io/document_format.i"
	@echo "... src/io/document_format.s"
	@echo "... src/io/text_reader.o"
	@echo "... src/io/text_reader.i"
	@echo "... src/io/text_reader.s"
	@echo "... src/lexicon/lexicon_builder.o"
	@echo "... src/lexicon/lexicon_builder.i"
	@echo "... src/lexicon/lexicon_builder.s"
	@echo "... src/lexicon/term_frequency_map.o"
	@echo "... src/lexicon/term_frequency_map.i"
	@echo "... src/lexicon/term_frequency_map.s"
	@echo "... src/model/greedy_parser.o"
	@echo "... src/model/greedy_parser.i"
	@echo "... src/model/greedy_parser.s"
	@echo "... src/mxnet-cpp/executor.o"
	@echo "... src/mxnet-cpp/executor.i"
	@echo "... src/mxnet-cpp/executor.s"
	@echo "... src/mxnet-cpp/io.o"
	@echo "... src/mxnet-cpp/io.i"
	@echo "... src/mxnet-cpp/io.s"
	@echo "... src/mxnet-cpp/kvstore.o"
	@echo "... src/mxnet-cpp/kvstore.i"
	@echo "... src/mxnet-cpp/kvstore.s"
	@echo "... src/mxnet-cpp/ndarray.o"
	@echo "... src/mxnet-cpp/ndarray.i"
	@echo "... src/mxnet-cpp/ndarray.s"
	@echo "... src/mxnet-cpp/operator.o"
	@echo "... src/mxnet-cpp/operator.i"
	@echo "... src/mxnet-cpp/operator.s"
	@echo "... src/mxnet-cpp/optimizer.o"
	@echo "... src/mxnet-cpp/optimizer.i"
	@echo "... src/mxnet-cpp/optimizer.s"
	@echo "... src/mxnet-cpp/symbol.o"
	@echo "... src/mxnet-cpp/symbol.i"
	@echo "... src/mxnet-cpp/symbol.s"
	@echo "... src/parser/arc_standard_transitions.o"
	@echo "... src/parser/arc_standard_transitions.i"
	@echo "... src/parser/arc_standard_transitions.s"
	@echo "... src/parser/parser_state.o"
	@echo "... src/parser/parser_state.i"
	@echo "... src/parser/parser_state.s"
	@echo "... src/parser/parser_transitions.o"
	@echo "... src/parser/parser_transitions.i"
	@echo "... src/parser/parser_transitions.s"
	@echo "... src/parser/tagger_transitions.o"
	@echo "... src/parser/tagger_transitions.i"
	@echo "... src/parser/tagger_transitions.s"
	@echo "... src/sentence_batch.o"
	@echo "... src/sentence_batch.i"
	@echo "... src/sentence_batch.s"
	@echo "... src/utils/registry.o"
	@echo "... src/utils/registry.i"
	@echo "... src/utils/registry.s"
	@echo "... src/utils/shared_store.o"
	@echo "... src/utils/shared_store.i"
	@echo "... src/utils/shared_store.s"
	@echo "... src/utils/task_context.o"
	@echo "... src/utils/task_context.i"
	@echo "... src/utils/task_context.s"
	@echo "... src/utils/task_spec.o"
	@echo "... src/utils/task_spec.i"
	@echo "... src/utils/task_spec.s"
	@echo "... src/utils/utils.o"
	@echo "... src/utils/utils.i"
	@echo "... src/utils/utils.s"
	@echo "... src/utils/work_space.o"
	@echo "... src/utils/work_space.i"
	@echo "... src/utils/work_space.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

